"""create_watch_sessions_table

Revision ID: d8885a54737d
Revises: 0002_phase1_metadata
Create Date: 2026-06-16 00:57:56.898424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd8885a54737d'
down_revision: Union[str, None] = '0002_phase1_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_watch_sessions_video_user', 'watch_sessions', ['video_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index('uix_watch_sessions_video_user_null', 'watch_sessions', ['video_id'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_watch_sessions_video_user_null', table_name='watch_sessions', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index('uix_watch_sessions_video_user', table_name='watch_sessions', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_table('watch_sessions')
    # ### end Alembic commands ###

